id: P005497
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:54:47.089266
source_metadata:
  id: bdr:W00KG01661
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༡
  author: ''
  volumes:
    c82fcff11c2349e897abd2a021c708d1:
      image_group_id: I00KG02355
      title: ''
      volume_number: 1
      total_pages: 203
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
